language: node_js
node_js:
  - "0.11"
  - "0.10"

before_script:
- sudo apt-get update -q
- sudo apt-get install git-core g++ nodejs npm libprotobuf-dev libgoogle-perftools-dev libncurses5-dev libboost-all-dev curl libcurl3 libcurl4-openssl-dev --force-yes
- git clone --depth 1 -b v1.16.x https://github.com/rethinkdb/rethinkdb.git
- cd rethinkdb
- ./configure --allow-fetch
- make
- rethinkdb --version
- rethinkdb --driver-port 28015 --bind localhost &