language: node_js
node_js:
  - "0.11"

before_script:
- sudo add-apt-repository ppa:rethinkdb/ppa -y
- sudo apt-get update -q
- sudo apt-get install rethinkdb --force-yes
- rethinkdb --version
- rethinkdb &