language: node_js
node_js:
  - "0.11"
  - "0.10"

before_script:
- source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
- sudo apt-get update -q
- sudo apt-get install rethinkdb --force-yes
- rethinkdb --version
- rethinkdb &